/race_float/power_monitor_node:
    ros__parameters:
        voltage:
            # brief: device address
            address: "0x69"
            #
            gain: 1
            # 
            bitrate: 18
            # 
            mode: 1
            #
            channel: 1

        current:
            # brief: device address
            address: "0x69"
            #
            gain: 1
            # 
            bitrate: 18
            # 
            mode: 1
            #
            channel: 2

        system:
            #
            rate: 2
            # 
            voltage_ratio: 0.090082
            #
            current_ratio: 0.092147
            #
            current_offset: 2.5
            #
            current_scale: 0.066
            #
            voltage_warn: 15.0

        ros:
            #
            frame_id: float