/race_float/pwm_driver_node:
  ros__parameters:
    pwm_frequency: 47.2

    pwm_ms_bias: 0.1
    no_pwm_timeout: 10.0

    led_ch_list: [5]
    led_topic_list: [led_1]
    led_min_us: [1100]
    led_max_us: [1900]
    led_init_us: [1100]
