/race_float/world_odom_transform_node:
  ros__parameters:
    m_gps_wait_time: 30.0
    ## Bay Campus
    # datum_latitude: 41.491602
    # datum_longitude: -71.422054
    ## Allen Harbour
    # datum_latitude: 41.621605
    # datum_longitude: -71.411018
    ## Salt Pond
    # datum_latitude: 41.4271
    # datum_longitude: -71.4966
    ## Beach Pond
    datum_latitude: 41.573822
    datum_longitude: -71.787280
    
    # STATIONARY OPTIMIZATION: 
    # Set to 2.0m to match the observed 1-2m GPS walking radius. 
    # This helps the EKF classify the drift as noise.
    position_accuracy: 2.0
    
    acceptable_var: 10.0
    mag_declination_auto: false
    mag_declination: 0.0
    manual_position_covariance: -1.0
    datum_manual_start: true